#mysql ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  #DB Source URL
spring.datasource.url=jdbc:mysql://localhost:3306/npvdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true

  #DB username
spring.datasource.username=root

  #DB password
spring.datasource.password=1234
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

  #file setting
spring.servlet.multipart.max-file-size= 10MB
spring.servlet.multipart.max-request-size= 10MB

spring.servlet.multipart.location= /Users/gimseong-ug/Desktop/NPV/NPV_BACK/demo/images

jwt.header= Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
jwt.secret= c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK\
jwt.token-validity-in-seconds= 86400



logging.level.me.silvernine= DEBUG
